#!/usr/bin/env perl

use strict;
use Finance::Quote;

my $METHOD = 'bourso';

my $q = Finance::Quote->new or die;

foreach my $stock (@ARGV) {
	my %info = $q->fetch($METHOD, $stock);
	print "Results for $stock :\n";
	foreach (sort keys %info) {
		my ($st, $attr) = split('\034', $_);
		print $attr . " => " . $info{$stock, $attr} . "\n";
	}
	print "\n";
}


