#!/bin/sh

# Extract an archive with file-roller and remove it if wanted.

# This script has been designed to work with Nautilus or Rox-Filer.
# It can also be used from command line.

test_bin() {
	if [ -z $(which $1) ]; then
		echo "ERROR: $1 not found!"
		echo "$0 requires $1 to work."
		exit 1
	fi
}

extract_gvfs() {
	file-roller --extract-here "$1"

	zenity --question --text="Do you want to remove "$(basename "$1")" ?"
		
	[ $? -eq 0 ] && gvfs-rm -f "$1"
}

extract_rm() {
	file-roller --extract-here "$1"

	# Zenity can be a little slow to start, so we use xmessage instead.
	xmessage -buttons Yes:0,No:2 -default Yes -nearmouse \
		"Do you want to remove "$(basename "$1")" ?"

	[ $? -eq 0 ] && rm -f "$1"
}

test_bin file-roller

PARENT=$(ps -p $PPID -o comm=)

if [ $PARENT = "nautilus" ]; then
	test_bin gvfs-rm
	test_bin zenity
	for F in $NAUTILUS_SCRIPT_SELECTED_URIS; do
		extract_gvfs "$F"
	done
else
	test_bin xmessage
	for F in "$@"; do
		extract_rm "$F"
	done
fi
