#!/bin/sh

# Extract an archive with file-roller and remove it if wanted.

# This script has been designed to work with Nautilus or Rox-Filer.
# It can also be used from command line.
# If you use it with Nautilus, beware that it only works with local files.

set -e

test_bin() {
	if [ -z $(which $1) ]; then
		echo "ERROR: $1 not found!"
		echo "$0 requires $1 to work."
		exit 1
	fi
}

INPUT="$1"
PARENT=$(ps -p $PPID -o comm=)

if [ $PARENT = "nautilus" ]; then
	INPUT="$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"
fi

[ -z $INPUT ] && exit 1

test_bin file-roller
test_bin xmessage

file-roller --extract-here "$INPUT"

# Zenity can be a little slow to start, so we use xmessage instead.
xmessage -buttons Yes:22,No:44 -default Yes -nearmouse \
	"Do you want to remove "$(basename "$INPUT")" ?"

[ $? -eq 22 ] && rm -f "$INPUT"

